// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/RdStation.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableIcons.ts";
import * as $$$3 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$3 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$8 from "./sections/Content/Benefits.tsx";
import * as $$$$$$9 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$10 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$11 from "./sections/Content/Faq.tsx";
import * as $$$$$$12 from "./sections/Content/Features.tsx";
import * as $$$$$$13 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$14 from "./sections/Content/Intro.tsx";
import * as $$$$$$15 from "./sections/Content/Logos.tsx";
import * as $$$$$$16 from "./sections/Content/Partners.tsx";
import * as $$$$$$17 from "./sections/Content/RichText.tsx";
import * as $$$$$$18 from "./sections/Content/Table.tsx";
import * as $$$$$$19 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$20 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$21 from "./sections/Footer/Footer.tsx";
import * as $$$$$$22 from "./sections/Gallery.tsx";
import * as $$$$$$23 from "./sections/Header/Header.tsx";
import * as $$$$$$24 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$25 from "./sections/Images/Carousel.tsx";
import * as $$$$$$26 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$27 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$28 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$29 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$30 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$31 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$32 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$33 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$34 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$35 from "./sections/Product/NotFound.tsx";
import * as $$$$$$36 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$37 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$38 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$39 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$40 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$41 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$42 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$43 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$44 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$48 from "./sections/territorio/TS-Cards.tsx";
import * as $$$$$$49 from "./sections/territorio/TS-CookieConsent.tsx";
import * as $$$$$$50 from "./sections/territorio/TS-CourseAccess.tsx";
import * as $$$$$$51 from "./sections/territorio/TS-CourseFit.tsx";
import * as $$$$$$52 from "./sections/territorio/TS-CourseFooter.tsx";
import * as $$$$$$53 from "./sections/territorio/TS-CourseHero.tsx";
import * as $$$$$$46 from "./sections/territorio/TS-CTABanner.tsx";
import * as $$$$$$47 from "./sections/territorio/TS-CTAButton.tsx";
import * as $$$$$$54 from "./sections/territorio/TS-CursoDominar.tsx";
import * as $$$$$$55 from "./sections/territorio/TS-Cursos.tsx";
import * as $$$$$$56 from "./sections/territorio/TS-ExpertQuotes.tsx";
import * as $$$$$$57 from "./sections/territorio/TS-Experts.tsx";
import * as $$$$$$58 from "./sections/territorio/TS-ExtraBonus.tsx";
import * as $$$$$$59 from "./sections/territorio/TS-Faq.tsx";
import * as $$$$$$60 from "./sections/territorio/TS-Header.tsx";
import * as $$$$$$61 from "./sections/territorio/TS-Hero.tsx";
import * as $$$$$$62 from "./sections/territorio/TS-LearnAlso.tsx";
import * as $$$$$$63 from "./sections/territorio/TS-Newsletter.tsx";
import * as $$$$$$64 from "./sections/territorio/TS-ParallaxWrapper.tsx";
import * as $$$$$$65 from "./sections/territorio/TS-Platform.tsx";
import * as $$$$$$66 from "./sections/territorio/TS-Policy.tsx";
import * as $$$$$$67 from "./sections/territorio/TS-Proposito.tsx";
import * as $$$$$$68 from "./sections/territorio/TS-SpecialConditions.tsx";
import * as $$$$$$69 from "./sections/territorio/TS-Territorios.tsx";
import * as $$$$$$70 from "./sections/territorio/TS-Testimonials.tsx";
import * as $$$$$$71 from "./sections/territorio/TS-Video.tsx";
import * as $$$$$$72 from "./sections/territorio/TS-Warranty.tsx";
import * as $$$$$$73 from "./sections/territorio/TS-WhyLearnWithExpert.tsx";
import * as $$$$$$74 from "./sections/territorio/TS-Zendesk.tsx";
import * as $$$$$$75 from "./sections/territorio/TSFooter.tsx";
import * as $$$$$$45 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/territorio/loaders/availableIcons.ts": $$$2,
    "deco-sites/territorio/loaders/icons.ts": $$$3,
    "deco-sites/territorio/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/territorio/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/territorio/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/territorio/sections/Cards/IconCardsCarousel.tsx": $$$$$$1,
    "deco-sites/territorio/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$2,
    "deco-sites/territorio/sections/Cards/ImageCardsCarousel.tsx": $$$$$$3,
    "deco-sites/territorio/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$4,
    "deco-sites/territorio/sections/Category/CategoryBanner.tsx": $$$$$$5,
    "deco-sites/territorio/sections/Category/CategoryGrid.tsx": $$$$$$6,
    "deco-sites/territorio/sections/Category/CategoryList.tsx": $$$$$$7,
    "deco-sites/territorio/sections/Content/Benefits.tsx": $$$$$$8,
    "deco-sites/territorio/sections/Content/BlogPosts.tsx": $$$$$$9,
    "deco-sites/territorio/sections/Content/CallToAction.tsx": $$$$$$10,
    "deco-sites/territorio/sections/Content/Faq.tsx": $$$$$$11,
    "deco-sites/territorio/sections/Content/Features.tsx": $$$$$$12,
    "deco-sites/territorio/sections/Content/ImageSection.tsx": $$$$$$13,
    "deco-sites/territorio/sections/Content/Intro.tsx": $$$$$$14,
    "deco-sites/territorio/sections/Content/Logos.tsx": $$$$$$15,
    "deco-sites/territorio/sections/Content/Partners.tsx": $$$$$$16,
    "deco-sites/territorio/sections/Content/RichText.tsx": $$$$$$17,
    "deco-sites/territorio/sections/Content/Table.tsx": $$$$$$18,
    "deco-sites/territorio/sections/Content/Testimonials.tsx": $$$$$$19,
    "deco-sites/territorio/sections/Content/TextWithImage.tsx": $$$$$$20,
    "deco-sites/territorio/sections/Footer/Footer.tsx": $$$$$$21,
    "deco-sites/territorio/sections/Gallery.tsx": $$$$$$22,
    "deco-sites/territorio/sections/Header/Header.tsx": $$$$$$23,
    "deco-sites/territorio/sections/Images/BannerGrid.tsx": $$$$$$24,
    "deco-sites/territorio/sections/Images/Carousel.tsx": $$$$$$25,
    "deco-sites/territorio/sections/Images/ImageGallery.tsx": $$$$$$26,
    "deco-sites/territorio/sections/Images/ShoppableBanner.tsx": $$$$$$27,
    "deco-sites/territorio/sections/Links/LinkTree.tsx": $$$$$$28,
    "deco-sites/territorio/sections/Links/Shortcuts.tsx": $$$$$$29,
    "deco-sites/territorio/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$30,
    "deco-sites/territorio/sections/Miscellaneous/CookieConsent.tsx": $$$$$$31,
    "deco-sites/territorio/sections/Miscellaneous/Slide.tsx": $$$$$$32,
    "deco-sites/territorio/sections/Newsletter/Newsletter.tsx": $$$$$$33,
    "deco-sites/territorio/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$34,
    "deco-sites/territorio/sections/Product/NotFound.tsx": $$$$$$35,
    "deco-sites/territorio/sections/Product/NotFoundChallenge.tsx": $$$$$$36,
    "deco-sites/territorio/sections/Product/ProductDetails.tsx": $$$$$$37,
    "deco-sites/territorio/sections/Product/ProductShelf.tsx": $$$$$$38,
    "deco-sites/territorio/sections/Product/ProductShelfTabbed.tsx": $$$$$$39,
    "deco-sites/territorio/sections/Product/SearchResult.tsx": $$$$$$40,
    "deco-sites/territorio/sections/Product/ShelfWithImage.tsx": $$$$$$41,
    "deco-sites/territorio/sections/Product/Wishlist.tsx": $$$$$$42,
    "deco-sites/territorio/sections/Social/InstagramPosts.tsx": $$$$$$43,
    "deco-sites/territorio/sections/Social/WhatsApp.tsx": $$$$$$44,
    "deco-sites/territorio/sections/territorio/TS-Cards.tsx": $$$$$$48,
    "deco-sites/territorio/sections/territorio/TS-CookieConsent.tsx": $$$$$$49,
    "deco-sites/territorio/sections/territorio/TS-CourseAccess.tsx": $$$$$$50,
    "deco-sites/territorio/sections/territorio/TS-CourseFit.tsx": $$$$$$51,
    "deco-sites/territorio/sections/territorio/TS-CourseFooter.tsx": $$$$$$52,
    "deco-sites/territorio/sections/territorio/TS-CourseHero.tsx": $$$$$$53,
    "deco-sites/territorio/sections/territorio/TS-CTABanner.tsx": $$$$$$46,
    "deco-sites/territorio/sections/territorio/TS-CTAButton.tsx": $$$$$$47,
    "deco-sites/territorio/sections/territorio/TS-CursoDominar.tsx": $$$$$$54,
    "deco-sites/territorio/sections/territorio/TS-Cursos.tsx": $$$$$$55,
    "deco-sites/territorio/sections/territorio/TS-ExpertQuotes.tsx": $$$$$$56,
    "deco-sites/territorio/sections/territorio/TS-Experts.tsx": $$$$$$57,
    "deco-sites/territorio/sections/territorio/TS-ExtraBonus.tsx": $$$$$$58,
    "deco-sites/territorio/sections/territorio/TS-Faq.tsx": $$$$$$59,
    "deco-sites/territorio/sections/territorio/TS-Header.tsx": $$$$$$60,
    "deco-sites/territorio/sections/territorio/TS-Hero.tsx": $$$$$$61,
    "deco-sites/territorio/sections/territorio/TS-LearnAlso.tsx": $$$$$$62,
    "deco-sites/territorio/sections/territorio/TS-Newsletter.tsx": $$$$$$63,
    "deco-sites/territorio/sections/territorio/TS-ParallaxWrapper.tsx":
      $$$$$$64,
    "deco-sites/territorio/sections/territorio/TS-Platform.tsx": $$$$$$65,
    "deco-sites/territorio/sections/territorio/TS-Policy.tsx": $$$$$$66,
    "deco-sites/territorio/sections/territorio/TS-Proposito.tsx": $$$$$$67,
    "deco-sites/territorio/sections/territorio/TS-SpecialConditions.tsx":
      $$$$$$68,
    "deco-sites/territorio/sections/territorio/TS-Territorios.tsx": $$$$$$69,
    "deco-sites/territorio/sections/territorio/TS-Testimonials.tsx": $$$$$$70,
    "deco-sites/territorio/sections/territorio/TS-Video.tsx": $$$$$$71,
    "deco-sites/territorio/sections/territorio/TS-Warranty.tsx": $$$$$$72,
    "deco-sites/territorio/sections/territorio/TS-WhyLearnWithExpert.tsx":
      $$$$$$73,
    "deco-sites/territorio/sections/territorio/TS-Zendesk.tsx": $$$$$$74,
    "deco-sites/territorio/sections/territorio/TSFooter.tsx": $$$$$$75,
    "deco-sites/territorio/sections/Theme/Theme.tsx": $$$$$$45,
  },
  "actions": {
    "deco-sites/territorio/actions/RdStation.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/territorio/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/territorio/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/territorio",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
